// Criar um Usuário (POST)
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Amilcar Fonseca",
    "email": "amilcar@gmail.com",
    "telefone": "68123"
}

// Listar Todos os Usuários (GET)
GET http://localhost:3000/usuarios

// Buscar um Usuário por ID (GET)
GET http://localhost:3000/usuarios/1

// Buscar um Usuário por Email (GET)
GET http://localhost:3000/usuarios/amilcar@gmail.com

// Atualizar um Usuário (PUT)
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "João Atualizado",
    "email": "joao_atualizado@example.com",
    "telefone": "987654321"
}

// Deletar um Usuário (DELETE)
DELETE http://localhost:3000/usuarios/1
